---
# 开发环境
spring:
  profiles: dev

remoting:
  web: http://localhost:8090/web

logging:
  path: ./
  file: ${spring.application.name}.log

---
# 测试环境
spring:
  profiles: test

remoting:
  web: http://istio-web/web

logging:
  path: /logs/
  file: ${spring.application.name}.log